//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Dnevnik
{
    using System;
    using System.Collections.Generic;
    
    public partial class DnevnaAktivnost
    {
        public int idDnevnaAktivnost { get; set; }
        public string nazivaktivnosti { get; set; }
        public string opisaktivnosti { get; set; }
        public System.DateTime datumobavljeneaktivnosti { get; set; }
        public int brojsamostalnihzahvata { get; set; }
        public int brojzahvatauznadzor { get; set; }
        public int Dogadjaj_idDogadjaj { get; set; }
    
        public virtual Dogadjaj Dogadjaj { get; set; }
    }
}
