//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Dnevnik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogadjaj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dogadjaj()
        {
            this.DnevnaAktivnost = new HashSet<DnevnaAktivnost>();
            this.ProvjeraZnanja = new HashSet<ProvjeraZnanja>();
            this.SlucajBolesnika = new HashSet<SlucajBolesnika>();
        }
    
        public int idDogadjaj { get; set; }
        public string nazivdogadjaja { get; set; }
        public string statusdogadjaja { get; set; }
        public System.DateTime datumodrzavanja { get; set; }
        public int TipDogadjaja_idTipDogadjaja { get; set; }
        public int Korisnik_idKorisnik { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DnevnaAktivnost> DnevnaAktivnost { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        public virtual TipDogadjaja TipDogadjaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProvjeraZnanja> ProvjeraZnanja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlucajBolesnika> SlucajBolesnika { get; set; }
    }
}
