//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Dnevnik
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class PI2205_DBEntities : DbContext
    {
        public PI2205_DBEntities()
            : base("name=PI2205_DBEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Biljeske> Biljeske { get; set; }
        public virtual DbSet<DnevnaAktivnost> DnevnaAktivnost { get; set; }
        public virtual DbSet<Dogadjaj> Dogadjaj { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<PrijavaIspita> PrijavaIspita { get; set; }
        public virtual DbSet<ProgramSpecijalizacije> ProgramSpecijalizacije { get; set; }
        public virtual DbSet<ProvjeraZnanja> ProvjeraZnanja { get; set; }
        public virtual DbSet<SlucajBolesnika> SlucajBolesnika { get; set; }
        public virtual DbSet<StrucniRad> StrucniRad { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipDogadjaja> TipDogadjaja { get; set; }
        public virtual DbSet<Uloga> Uloga { get; set; }
    }
}