//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Dnevnik
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvjeraZnanja
    {
        public int idProvjeraZnanja { get; set; }
        public System.DateTime datumprovjere { get; set; }
        public string pitanja { get; set; }
        public int ocjena { get; set; }
        public int Dogadjaj_idDogadjaj { get; set; }
    
        public virtual Dogadjaj Dogadjaj { get; set; }
    }
}
