//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Dnevnik
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlucajBolesnika
    {
        public int idSlucajBolesnika { get; set; }
        public string vrstaosobe { get; set; }
        public string opisslucaja { get; set; }
        public System.DateTime datumpregleda { get; set; }
        public string dijagnoza { get; set; }
        public int Dogadjaj_idDogadjaj { get; set; }
    
        public virtual Dogadjaj Dogadjaj { get; set; }
    }
}
